export const ReactQueryKey = {
    Company: "Company",
    ActiveCompany: "ActiveCompany",
    SupplierGroup: "SupplierGroup",
    Supplier: "Supplier",
    AccountVoucher: "AccountVoucher",
    TransactionTypes: "TransactionTypes",
    Projects: "Projects",
    PaymentMethods: "PaymentMethods",
    ChartOfAccounts: "ChartOfAccounts",
    CashFlowCategories: "CashFlowCategories",
    AccountCategories: "AccountCategories",
    AccountTypes: "AccountTypes",
    Taxs: "Taxs",
    PaymentTerms: 'PaymentTerms',
    Country: 'Country',
    Currency: 'Currency',
    Material: 'Material',
    Uom: 'Uom',
    Buyer: 'Buyer',
    MasterLC: 'MasterLC',
    VoucherTypes: 'VoucherTypes',
    Role: 'Role',
    User: 'User',

};