export type IGatePassSaveDto = {
    id: number,
    gatepassNo: string,
    date: Date,
    itemType: string,
    itemTypeId: number,
    gmtType: string,
    gmtTypeId: number,
    gatePassType: string,
    gatePassTypeId: number,
    sender: string,
    senderId: number,
    senderPhoneNo: string,
    carriedById: number,
    carriedBy: string,
    department: string,
    departmentId: number,
    supplier: string,
    supplierId: number,
    details?: IGatePassDetailsSaveDto[]
}

export type IGatePassDetailsSaveDto = {
    id: number,
    buyer: string,
    buyerId: number,
    style: string,
    styleId: number,
    po: string,
    poId: number,
    program: string,
    programId: number,
    item: string,
    itemId: number,
    color: string,
    colorId: number,
    size: string,
    sizeId: number,
    quantity: number,
    uom: string,
    uomId: number,
}